#ifndef CARPKEYBOARD_HH
#define CARPKEYBOARD_HH

#include "carptype.h"

typedef enum CarpKeyboardKey
{
    CarpKeyboardKey_Invalid = -1,
    CarpKeyboardKey_Backspace = 8,
    CarpKeyboardKey_Tab = 9,
    CarpKeyboardKey_Enter = 13,

    CarpKeyboardKey_Shift = 16,
    CarpKeyboardKey_Ctrl = 17,
    CarpKeyboardKey_Alt = 18,
    CarpKeyboardKey_Menu = 19,

    CarpKeyboardKey_Escape = 27,
    CarpKeyboardKey_Space = 32,
    CarpKeyboardKey_Exclaim = 33,
    CarpKeyboardKey_Quotedbl = 34,
    CarpKeyboardKey_Hash = 35,
    CarpKeyboardKey_Dollar = 36,
    CarpKeyboardKey_Percent = 37,
    CarpKeyboardKey_Ampersand = 38,
    CarpKeyboardKey_Quote = 39,
    CarpKeyboardKey_LeftParen = 40,
    CarpKeyboardKey_RightParen = 41,
    CarpKeyboardKey_Asterisk = 42,
    CarpKeyboardKey_Plus = 43,
    CarpKeyboardKey_Comma = 44,
    CarpKeyboardKey_Minus = 45,
    CarpKeyboardKey_Period = 46,
    CarpKeyboardKey_Slash = 47,
    CarpKeyboardKey_Num0 = 48,
    CarpKeyboardKey_Num1 = 49,
    CarpKeyboardKey_Num2 = 50,
    CarpKeyboardKey_Num3 = 51,
    CarpKeyboardKey_Num4 = 52,
    CarpKeyboardKey_Num5 = 53,
    CarpKeyboardKey_Num6 = 54,
    CarpKeyboardKey_Num7 = 55,
    CarpKeyboardKey_Num8 = 56,
    CarpKeyboardKey_Num9 = 57,
    CarpKeyboardKey_Colon = 58,
    CarpKeyboardKey_Semicolon = 59,
    CarpKeyboardKey_Less = 60,
    CarpKeyboardKey_Equals = 61,
    CarpKeyboardKey_Greater = 62,
    CarpKeyboardKey_Question = 63,
    CarpKeyboardKey_At = 64,
    CarpKeyboardKey_LeftBracket = 91,
    CarpKeyboardKey_Backslash = 92,
    CarpKeyboardKey_RightBracket = 93,
    CarpKeyboardKey_Caret = 94,
    CarpKeyboardKey_Underscore = 95,
    CarpKeyboardKey_Backquote = 96,

    CarpKeyboardKey_A = 65,
    CarpKeyboardKey_B,
    CarpKeyboardKey_C,
    CarpKeyboardKey_D,
    CarpKeyboardKey_E,
    CarpKeyboardKey_F,
    CarpKeyboardKey_G,
    CarpKeyboardKey_H,
    CarpKeyboardKey_I,
    CarpKeyboardKey_J,
    CarpKeyboardKey_K,
    CarpKeyboardKey_L,
    CarpKeyboardKey_M,
    CarpKeyboardKey_N,
    CarpKeyboardKey_O,
    CarpKeyboardKey_P,
    CarpKeyboardKey_Q,
    CarpKeyboardKey_R,
    CarpKeyboardKey_S,
    CarpKeyboardKey_T,
    CarpKeyboardKey_U,
    CarpKeyboardKey_V,
    CarpKeyboardKey_W,
    CarpKeyboardKey_X,
    CarpKeyboardKey_Y,
    CarpKeyboardKey_Z,
    CarpKeyboardKey_Delete = 127,
    CarpKeyboardKey_CapsLock = 128,
    CarpKeyboardKey_F1,
    CarpKeyboardKey_F2,
    CarpKeyboardKey_F3,
    CarpKeyboardKey_F4,
    CarpKeyboardKey_F5,
    CarpKeyboardKey_F6,
    CarpKeyboardKey_F7,
    CarpKeyboardKey_F8,
    CarpKeyboardKey_F9,
    CarpKeyboardKey_F10,
    CarpKeyboardKey_F11,
    CarpKeyboardKey_F12,

    CarpKeyboardKey_PrintScreen,
    CarpKeyboardKey_ScrollLock,
    CarpKeyboardKey_Pause,
    CarpKeyboardKey_Insert,
    CarpKeyboardKey_Home,
    CarpKeyboardKey_PageUp,
    CarpKeyboardKey_End,
    CarpKeyboardKey_PageDown,

    CarpKeyboardKey_Right,
    CarpKeyboardKey_Left,
    CarpKeyboardKey_Down,
    CarpKeyboardKey_Up,
    CarpKeyboardKey_NumLockClear,
    CarpKeyboardKey_KpDivide,
    CarpKeyboardKey_KpMultiply,
    CarpKeyboardKey_KpMinus,
    CarpKeyboardKey_KpPlus,
    CarpKeyboardKey_KpEnter,
    CarpKeyboardKey_KpPeriod,
    CarpKeyboardKey_KpEquals,
    CarpKeyboardKey_KpComma,
    CarpKeyboardKey_Kp1,
    CarpKeyboardKey_Kp2,
    CarpKeyboardKey_Kp3,
    CarpKeyboardKey_Kp4,
    CarpKeyboardKey_Kp5,
    CarpKeyboardKey_Kp6,
    CarpKeyboardKey_Kp7,
    CarpKeyboardKey_Kp8,
    CarpKeyboardKey_Kp9,
    CarpKeyboardKey_Kp0,

    CarpKeyboardKey_Undo,
    CarpKeyboardKey_Cut,
    CarpKeyboardKey_Copy,
    CarpKeyboardKey_Paste,

    CarpKeyboardKey_Mute,
    CarpKeyboardKey_VolumeUp,
    CarpKeyboardKey_VolumeDown,

    CarpKeyboardKey_KpEqualsAS400,

    CarpKeyboardKey_LCtrl,
    CarpKeyboardKey_LShift,
    CarpKeyboardKey_LAlt,
    CarpKeyboardKey_LGui,
    CarpKeyboardKey_RCtrl,
    CarpKeyboardKey_RShift,
    CarpKeyboardKey_RAlt,
    CarpKeyboardKey_RGui,

    CarpKeyboardKey_Mode,
    CarpKeyboardKey_AudioNext,
    CarpKeyboardKey_AudioPrev,
    CarpKeyboardKey_AudioStop,
    CarpKeyboardKey_AudioPlay,
    CarpKeyboardKey_AudioMute,
    CarpKeyboardKey_MediaSelect,

    CarpKeyboardKey_MouseXButton1,
    CarpKeyboardKey_MouseXButton2,


} CarpKeyboardKey;

CARP_FN void carp_keyboard_resetState(void);
CARP_FN void carp_keyboard_setKeyState(CarpKeyboardKey key, bool down);

CARP_FN bool carp_keyboard_wasKeyPressed(CarpKeyboardKey key);
CARP_FN bool carp_keyboard_wasKeyReleased(CarpKeyboardKey key);
CARP_FN bool carp_keyboard_isKeyDown(CarpKeyboardKey key);

#endif // CARPKEYBOARD_HH
