#ifndef MYKEYS_HH
#define MYKEYS_HH

#include "mytype.h"

typedef enum MyKey
{
    MyKey_InvalidKey = -1,
    MyKey_Backspace = 8,
    MyKey_Tab = 9,
    MyKey_Enter = 13,

    MyKey_Shift = 16,
    MyKey_Ctrl = 17,
    MyKey_Alt = 18,
    MyKey_Menu = 19,

    MyKey_Escape = 27,
    MyKey_Space = 32,
    MyKey_Exclaim = 33,
    MyKey_Quotedbl = 34,
    MyKey_Hash = 35,
    MyKey_Dollar = 36,
    MyKey_Percent = 37,
    MyKey_Ampersand = 38,
    MyKey_Quote = 39,
    MyKey_LeftParen = 40,
    MyKey_RightParen = 41,
    MyKey_Asterisk = 42,
    MyKey_Plus = 43,
    MyKey_Comma = 44,
    MyKey_Minus = 45,
    MyKey_Period = 46,
    MyKey_Slash = 47,
    MyKey_Num0 = 48,
    MyKey_Num1 = 49,
    MyKey_Num2 = 50,
    MyKey_Num3 = 51,
    MyKey_Num4 = 52,
    MyKey_Num5 = 53,
    MyKey_Num6 = 54,
    MyKey_Num7 = 55,
    MyKey_Num8 = 56,
    MyKey_Num9 = 57,
    MyKey_Colon = 58,
    MyKey_Semicolon = 59,
    MyKey_Less = 60,
    MyKey_Equals = 61,
    MyKey_Greater = 62,
    MyKey_Question = 63,
    MyKey_At = 64,
    MyKey_LeftBracket = 91,
    MyKey_Backslash = 92,
    MyKey_RightBracket = 93,
    MyKey_Caret = 94,
    MyKey_Underscore = 95,
    MyKey_Backquote = 96,

    MyKey_A = 65,
    MyKey_B,
    MyKey_C,
    MyKey_D,
    MyKey_E,
    MyKey_F,
    MyKey_G,
    MyKey_H,
    MyKey_I,
    MyKey_J,
    MyKey_K,
    MyKey_L,
    MyKey_M,
    MyKey_N,
    MyKey_O,
    MyKey_P,
    MyKey_Q,
    MyKey_R,
    MyKey_S,
    MyKey_T,
    MyKey_U,
    MyKey_V,
    MyKey_W,
    MyKey_X,
    MyKey_Y,
    MyKey_Z,
    MyKey_Delete = 127,
    MyKey_CapsLock = 128,
    MyKey_F1,
    MyKey_F2,
    MyKey_F3,
    MyKey_F4,
    MyKey_F5,
    MyKey_F6,
    MyKey_F7,
    MyKey_F8,
    MyKey_F9,
    MyKey_F10,
    MyKey_F11,
    MyKey_F12,

    MyKey_PrintScreen,
    MyKey_ScrollLock,
    MyKey_Pause,
    MyKey_Insert,
    MyKey_Home,
    MyKey_PageUp,
    MyKey_End,
    MyKey_PageDown,

    MyKey_Right,
    MyKey_Left,
    MyKey_Down,
    MyKey_Up,
    MyKey_NumLockClear,
    MyKey_KpDivide,
    MyKey_KpMultiply,
    MyKey_KpMinus,
    MyKey_KpPlus,
    MyKey_KpEnter,
    MyKey_KpPeriod,
    MyKey_KpEquals,
    MyKey_KpComma,
    MyKey_Kp1,
    MyKey_Kp2,
    MyKey_Kp3,
    MyKey_Kp4,
    MyKey_Kp5,
    MyKey_Kp6,
    MyKey_Kp7,
    MyKey_Kp8,
    MyKey_Kp9,
    MyKey_Kp0,

    MyKey_Undo,
    MyKey_Cut,
    MyKey_Copy,
    MyKey_Paste,

    MyKey_Mute,
    MyKey_VolumeUp,
    MyKey_VolumeDown,

    MyKey_KpEqualsAS400,

    MyKey_LCtrl,
    MyKey_LShift,
    MyKey_LAlt,
    MyKey_LGui,
    MyKey_RCtrl,
    MyKey_RShift,
    MyKey_RAlt,
    MyKey_RGui,

    MyKey_Mode,
    MyKey_AudioNext,
    MyKey_AudioPrev,
    MyKey_AudioStop,
    MyKey_AudioPlay,
    MyKey_AudioMute,
    MyKey_MediaSelect,



} MyKey;

void carpKeys_resetState();
void carpKeys_setKeyState(MyKey key, bool down);

bool carpKeys_wasPressed(MyKey key);
bool carpKeys_wasReleased(MyKey key);
bool carpKeys_isDown(MyKey key);

#endif // MYKEYS_HH